ramu/tuition/urls.py
from django.contrib import admin
from django.urls import include,path
from django.contrib.auth import views as auth_views

from . import views
app_name = "tuition"

urlpatterns = [
    path("",views.index, name="index"),
    path("curriculum",views.curriculum, name="curriculum"),
    path("methodology",views.methodology, name="methodology"),
    path("about",views.about, name="about"),
    path("mission",views.mission, name="mission"),
    path("feedback",views.feedback, name="feedback"),
    path("enquiry",views.enquiry, name="enquiry"),
    # path("login",views.login_view, name="login"),
    # path('login/', auth_views.login, {'template_name': 'login.html'}, name='login'),
    path("login_view", views.login_view, name="login_view"),
    #path("logout",views.logout, name="logout"),
    path("post_feedback",views.post_feedback, name="post_feedback"),
    path("post_enquiry",views.post_enquiry, name="post_enquiry"),
    path('sign_up/',views.sign_up,name="sign_up"),
]

ramu/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import include,path
from django.views.generic.base import TemplateView

urlpatterns = [
    #path("",include('tuition.urls')),
    path('admin/', admin.site.urls),
    path('',include('django.contrib.auth.urls')),
    path('',include('tuition.urls')),
    path('', TemplateView.as_view(template_name='dashboard.html'), name='home'),
]

ramu/tuition/models.py
from django.db import models

# Create your models here.
class Feedback(models.Model):
    name = models.CharField(max_length=64)
    phone = models.CharField(max_length=16)
    email = models.CharField(max_length=128)
    feedback = models.CharField(max_length=3000)
    posted_on = models.DateField

    def __str__(self):
        return f"{self.name} ({self.feedback})"

class Enquiry(models.Model):
    name = models.CharField(max_length=64)
    phone = models.CharField(max_length=16)
    email = models.CharField(max_length=128)
    enquiry = models.CharField(max_length=3000)
    posted_on = models.DateField
    reply = models.CharField(max_length=3000)
    replied_on = models.DateField
    reply_id = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.id} - {self.name} - {self.enquiry} - {self.reply}"

ramu/tuition/forms.py
from django import forms

class NewFeedbackForm(forms.Form):
    name = forms.CharField(label='Name', max_length=100)
    phone = forms.CharField(label='Phone Number', max_length=100)
    email = forms.EmailField(label='Email Address', max_length=100)
    feedback = forms.CharField(label='Feedback', max_length=1000)

class NewEnquiryForm(forms.Form):
    name = forms.CharField(label='Name', max_length=100)
    phone = forms.CharField(label='Phone Number', max_length=100)
    email = forms.EmailField(label='Email Address', max_length=100)
    enquiry = forms.CharField(label='Feedback', max_length=1000)

ramu/tuition/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render
from django.http import HttpResponse,Http404, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from . forms import NewFeedbackForm, NewEnquiryForm
from . models import Feedback,Enquiry

#from .models import Flight, Passenger

# Create your views here.
def index(request):
    #return HttpResponse("Flights");
    if request.user.is_authenticated:
        context={
            "loggedin":True
        }
    else:
        context={
        "loggedin":False
        }
    return render(request, "tuition/index.html")

def curriculum(request):
    return render(request,"tuition/curriculum.html")

def methodology(request):
    return render(request,"tuition/methodology.html")

def about(request):
    return render(request,"tuition/about.html")

def mission(request):
    return render(request,"tuition/mission.html")

def feedback(request):
    return render(request,"tuition/feedback.html")

def enquiry(request):
    return render(request,"tuition/enquiry.html")

def post_feedback(request):
    if request.method == 'POST':
        form = NewFeedbackForm(request.POST)
        if form.is_valid():
            feedback = Feedback()
            feedback.name = form.cleaned_data['name']
            feedback.phone = form.cleaned_data['phone']
            feedback.email = form.cleaned_data['email']
            feedback.feedback = form.cleaned_data['feedback']
            feedback.save()
    return render(request,"tuition/feedback.html",{"message":"Feedback submitted successfully!"})

def post_enquiry(request):
    if request.method == 'POST':
        form = NewEnquiryForm(request.POST)
        if form.is_valid():
            enquiry = Enquiry()
            enquiry.name = form.cleaned_data['name']
            enquiry.phone = form.cleaned_data['phone']
            enquiry.email = form.cleaned_data['email']
            enquiry.enquiry = form.cleaned_data['enquiry']
            enquiry.save()
    return render(request,"tuition/enquiry.html",{"message":"Enquiry submitted successfully. We will get back soon!"})

# def logout(request):
#     return render(request,"tuition/enquiry.html")

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(email=email, password=password)
        if user is not None:
            form = LoginForm()
            login(request, user)
    return render(request,"tuition/login.html")

def sign_up(request):
    context = {}
    form = UserCreationForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            user = form.save()
            login(request,user)
            return render(request,'tuition/index.html')
    context['form']=form
    return render(request,'tuition/sign_up.html',context)

ramu/tuition/templates/base.html
<html>
<head>
  <title>{% block title %}Django Inbuild Auth{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
        # All the templates renders here dynamically according to   the route
    {% endblock %}
  </main>
</body>
</html>

ramu/tuition/templates/dashboard.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    {%comment%} Checks if use is logged in  {%endcomment%}
    {% if user.is_authenticated %}
      Hi {{ user.username }}!
      Your Email is {{ user.email }}
      <p><a href="{% url 'logout' %}">logout</a></p>
    {% else %}
      <p>You are not logged in</p>
      <a href="{% url 'login' %}">login</a>
    {% endif %}
{% endblock %}

ramu/tuition/templates/tuition/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr"  class="no-js">
  <head>
    <!-- Mobile Specific Meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Favicon -->
  <link rel="shortcut icon" href="img/fav.png" />
  <!-- Author Meta -->
  <meta name="author" content="colorlib" />
  <!-- Meta Description -->
  <meta name="description" content="" />
  <!-- Meta Keyword -->
  <meta name="keywords" content="" />
  <!-- meta character set -->
  <meta charset="UTF-8" />

    <title>{% block title %} {% endblock %}</title>

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:900|Roboto:400,400i,500,700" rel="stylesheet" />
  <!--
      CSS
      =============================================
    -->
  <link rel="stylesheet" href="{% static 'tuition/css/linearicons.css' %}" />
  <link rel="stylesheet" href="{% static 'tuition/css/font-awesome.min.css' %}" />
  <link rel="stylesheet" href="{% static 'tuition/css/bootstrap.css' %}" />
  <link rel="stylesheet" href="{% static 'tuition/css/magnific-popup.css' %}" />
  <link rel="stylesheet" href="{% static 'tuition/css/owl.carousel.css' %}" />
  <link rel="stylesheet" href="{% static 'tuition/css/nice-select.css' %}">
  <link rel="stylesheet" href="{% static 'tuition/css/hexagons.min.css' %}" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/themify-icons/0.1.2/css/themify-icons.css" />
  <link rel="stylesheet" href="{% static 'tuition/css/main.css' %}" />

  </head>
  <body>
    <!-- ================ Start Header Area ================= -->
<header class="default-header">
  <nav class="navbar navbar-expand-lg  navbar-light">
    <div class="container">
      <a class="navbar-brand" href="index.html">
        <img src="{% static 'tution/img/logo.png' %}" alt="" />
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="lnr lnr-menu"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end align-items-center" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li><a href="{% url 'tuition:index' %}">Home</a></li>
          <li><a href="{% url 'tuition:curriculum' %}">Curriculum</a></li>
          <li><a href="{% url 'tuition:methodology' %}">Teaching Methodology</a></li>
    <li><a href="{% url 'tuition:about' %}">About Us</a></li>
    <li><a href="{% url 'tuition:mission' %}">Mission</a></li>
          <li><a href="{% url 'tuition:feedback' %}">Feedback</a></li>
    <li><a href="{% url 'tuition:enquiry' %}">Enquiry</a></li>
     {% if user.is_authenticated %}
                     <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span class="glyphicon glyphicon-user"></span> Hi,  <!--<img src="{% url 'uploads/images') . '/Profile_picture_of_ashis.jpg'; ?>" height="30px" width="30px">-->{{ user }}<b class="caret"></b></a>
                                  <ul class="dropdown-menu">


                                          <li><a href="" style="color:red;">View Enquiries</a></li>

                  <br>
                                      <li><a href="" style="color:red;">View Feedback</a></li>
                  <br>
                                      <li><a href="{% url 'logout' %}" style="color:red;">Logout</a></li>
                                  </ul>
                              </li>

          {% else %}

                              <li><a href="{% url 'login' %}">Login</a> / <a href="{% url 'tuition:sign_up' %}">Register</a></li>

          {% endif %}

          <!--li>
            <button class="search">
              <span class="lnr lnr-magnifier" id="search"></span>
            </button>
          </li-->
        </ul>
      </div>
    </div>
  </nav>
  <div class="search-input" id="search-input-box">
    <div class="container">
      <form class="d-flex justify-content-between">
        <input type="text" class="form-control" id="search-input" placeholder="Search Here" />
        <button type="submit" class="btn"></button>
        <span class="lnr lnr-cross" id="close-search" title="Close Search"></span>
      </form>
    </div>
  </div>
</header>
<!-- ================ End Header Area ================= -->
    {% block body %}
    {% endblock %}
    <!-- Footer -->
    <!-- ================ start footer Area ================= -->
<footer class="footer-area section-gap">
  <div class="container">
    <div class="row">
      <div class="col-lg-2 col-md-6 single-footer-widget">
        <h4>Top Products</h4>
        <ul>
          <li><a href="#">Managed Website</a></li>
          <li><a href="#">Manage Reputation</a></li>
          <li><a href="#">Power Tools</a></li>
          <li><a href="#">Marketing Service</a></li>
        </ul>
      </div>
      <div class="col-lg-2 col-md-6 single-footer-widget">
        <h4>Quick Links</h4>
        <ul>
          <li><a href="#">Jobs</a></li>
          <li><a href="#">Brand Assets</a></li>
          <li><a href="#">Investor Relations</a></li>
          <li><a href="#">Terms of Service</a></li>
        </ul>
      </div>
      <div class="col-lg-2 col-md-6 single-footer-widget">
        <h4>Features</h4>
        <ul>
          <li><a href="#">Jobs</a></li>
          <li><a href="#">Brand Assets</a></li>
          <li><a href="#">Investor Relations</a></li>
          <li><a href="#">Terms of Service</a></li>
        </ul>
      </div>
      <div class="col-lg-2 col-md-6 single-footer-widget">
        <h4>Resources</h4>
        <ul>
          <li><a href="#">Guides</a></li>
          <li><a href="#">Research</a></li>
          <li><a href="#">Experts</a></li>
          <li><a href="#">Agencies</a></li>
        </ul>
      </div>
      <div class="col-lg-4 col-md-6 single-footer-widget">
        <h4>Newsletter</h4>
        <p>You can trust us. we only send promo offers,</p>
        <div class="form-wrap" id="mc_embed_signup">
          <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
            method="get" class="form-inline">
            <input class="form-control" name="EMAIL" placeholder="Your Email Address" onfocus="this.placeholder = ''"
              onblur="this.placeholder = 'Your Email Address '" required="" type="email">
            <button class="click-btn btn btn-default text-uppercase">subscribe</button>
            <div style="position: absolute; left: -5000px;">
              <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
            </div>

            <div class="info"></div>
          </form>
        </div>
      </div>
    </div>
    <div class="footer-bottom row align-items-center">

      <div class="col-lg-4 col-md-12 footer-social">
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-dribbble"></i></a>
        <a href="#"><i class="fa fa-behance"></i></a>
      </div>
    </div>
  </div>
</footer>
{{user}}
<!-- ================ End footer Area ================= -->

<!-- ================ End footer Area ================= -->

<script src="{% static 'tuition/js/vendor/jquery-2.2.4.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
  crossorigin="anonymous"></script>
<script src="{% static 'tuition/js/vendor/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
<script src="{% static 'tuition/js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'tuition/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'tuition/js/parallax.min.js' %}"></script>
<script src="{% static 'tuition/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'tuition/js/jquery.sticky.js' %}"></script>
<script src="{% static 'tuition/js/hexagons.min.js' %}"></script>
<script src="{% static 'tuition/js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'tuition/js/waypoints.min.js' %}"></script>
<script src="{% static 'tuition/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'tuition/js/main.js' %}"></script>

  </body>
</html>

ramu/tuition/templates/tuition/enquiry.html
{% extends "tuition/base.html" %}
{% load static %}
{% block title %}
Online Classes
{% endblock %}

{% block body %}

<!-- ================ start banner Area ================= -->
 <section class="banner-area">
   <div class="container">
     <div class="row justify-content-center align-items-center">
       <div class="col-lg-12 banner-right">
         <h1 class="text-white">
           About Us
         </h1>
         <p class="mx-auto text-white  mt-20 mb-40">
           In the history of modern astronomy, there is probably no one greater leap forward than the building.
         </p>
         <div class="link-nav">
           <span class="box">
             <a href="index.html">Home </a>
             <i class="lnr lnr-arrow-right"></i>
             <a href="about.html">About</a>
           </span>
         </div>
       </div>
     </div>
   </div>
 </section>
 <!-- ================ End banner Area ================= -->

 <!-- ================ Start Feature Area ================= -->
 <section class="feature-area">
   <section class="feature-area">
     <div class="container-fluid">
       <div class="feature-inner row">
         <div class="col-lg-4 col-md-6">
           <div class="feature-item d-flex">
             <i class="ti-book"></i>
             <div class="ml-20">
               <div class="course-form-section">
                 {% if message %}
                         <div class="alert alert-warning"><p style="color:orange">{{message}}</p></div>
                     {% endif %}
             <h3 >Enquiry</h3>
             <p >Have doubt? Ask us!</p>
             <form class="course-form-area contact-page-form course-form text-right" id="myForm" name="myForm" action="{% url 'tuition:post_enquiry' %}" method="post">
               {% csrf_token %}
               <div class="form-group col-md-12">
                 <input type="text" class="form-control" id="name" name="name" placeholder="Name" onfocus="this.placeholder = ''"
                  onblur="this.placeholder = 'Name'">
               </div>
               <div class="form-group col-md-12">
                 <input type="text" class="form-control" id="subject" name="phone" placeholder="Phone Number" onfocus="this.placeholder = ''"
                  onblur="this.placeholder = 'Phone Number'">
               </div>
               <div class="form-group col-md-12">
                 <input type="email" class="form-control" id="email" name="email" placeholder="Email Address" onfocus="this.placeholder = ''"
                  onblur="this.placeholder = 'Email Address'">
               </div>
 			  <div class="form-group col-md-12">
                 <input type="textarea" rows=5 class="form-control" id="enquiry" name="enquiry" placeholder="Enquiry" onfocus="this.placeholder = ''"
                  onblur="this.placeholder = 'Enquiry'">
               </div>
               <div class="col-lg-12 text-center">
                 <button class="btn text-uppercase">Submit</button>
               </div>
             </form>
           </div>
             </div>
           </div>
         </div>

       </div>
     </div>
   </section>
 </section>
 <!-- ================ End Feature Area ================= -->

 <!-- ================- Start About Area ================= -->
 <section class="about-area section-gap">
   <div class="container">
     <div class="row align-items-center justify-content-center">
       <div class="col-lg-5 col-md-6 about-left">
         <img class="img-fluid" src="{% static 'img/about-img.jpg' %} alt="">
       </div>
       <div class="offset-lg-1 col-lg-5 col-md-12 about-right">
         <h1>
           Over all <br>
           2500 Courses <br>
           from 20 Platforms
         </h1>
         <div>
           <p>
             There is a moment in the life of any aspiring astronomer that it is time to buy that first telescope.
             It’s exciting to think about setting up your own viewing station. In the life of any aspiring astronomer
             that it is time to buy that first telescope. It’s exciting to think about setting up your own viewing
             station.
           </p>
           <p>
             It’s exciting to think about setting up your own viewing station. In the life of any aspiring astronomer
             that it is time to buy that first telescope exciting is time to buy that first.
           </p>
         </div>
       </div>
     </div>
   </div>
 </section>
 <!-- ================- End About Area ================= -->

 <!-- ================ Start Video Area ================= -->
 <section class="video-area section-gap-bottom">
   <div class="container">
     <div class="row align-items-center">
       <div class="col-lg-5">
         <div class="section-title text-white">
           <h2 class="text-white">
             Watch Our Trainers <br>
             in Live Action
           </h2>
           <p>
             In the history of modern astronomy, there is probably no one greater leap forward than the building and
             launch of the space telescope known as the Hubble.
           </p>
         </div>
       </div>
       <div class="offset-lg-1 col-md-6 video-left">
         <div class="owl-carousel video-carousel">
           <div class="single-video">
             <div class="video-part">
               <img class="img-fluid" src="{% static 'img/video-img.jpg' %} alt="">
               <div class="overlay"></div>
               <a class="popup-youtube play-btn" href="https://www.youtube.com/watch?v=VufDd-QL1c0">
                 <img class="play-icon" src="{% static 'img/play-btn.jpg' %} alt="">
               </a>
             </div>
             <h4 class="text-white mb-20 mt-30">Learn Angular js Course for Legendary Persons</h4>
             <p class="text-white mb-20">
               In the history of modern astronomy, there is probably no one greater leap forward than the building and
               launch of the space telescope known as the Hubble.
             </p>
           </div>

           <div class="single-video">
             <div class="video-part">
               <img class="img-fluid" src="{% static 'img/video-img.jpg' %} alt="">
               <div class="overlay"></div>
               <a class="popup-youtube play-btn" href="https://www.youtube.com/watch?v=VufDd-QL1c0">
                 <img class="play-icon" src="{% static 'img/play-btn.jpg' %} alt="">
               </a>
             </div>
             <h4 class="text-white mb-20 mt-30">Learn Angular js Course for Legendary Persons</h4>
             <p class="text-white mb-20">
               In the history of modern astronomy, there is probably no one greater leap forward than the building and
               launch of the space telescope known as the Hubble.
             </p>
           </div>
         </div>
       </div>
     </div>
   </div>
 </section>
 <!-- ================ End Video Area ================= -->

 <!-- ================ Start Feature Area ================= -->
 <section class="other-feature-area">
   <div class="container">
     <div class="feature-inner row">
       <div class="col-lg-12">
         <div class="section-title text-left">
           <h2>
             Features That <br />
             Can Avail By Everyone
           </h2>
           <p>
             If you are looking at blank cassettes on the web, you may be
             very confused at the difference in price. You may see some for
             as low as $.17 each.
           </p>
         </div>
       </div>
       <div class="col-lg-4 col-md-6">
         <div class="other-feature-item">
           <i class="ti-key"></i>
           <h4>Lifetime Access</h4>
           <div>
             <p>
               Lorem ipsum dolor sit amet consec tetur adipisicing elit, sed
               do eiusmod tempor incididunt labore. Lorem ipsum dolor sit
               amet consec tetur adipisicing elit, sed do eiusmod tempor
               incididunt labore.
             </p>
           </div>
         </div>
       </div>
       <div class="col-lg-4 col-md-6 mt--160">
         <div class="other-feature-item">
           <i class="ti-files"></i>
           <h4>Source File Included</h4>
           <div>
             <p>
               Lorem ipsum dolor sit amet consec tetur adipisicing elit, sed
               do eiusmod tempor incididunt labore. Lorem ipsum dolor sit
               amet consec tetur adipisicing elit, sed do eiusmod tempor
               incididunt labore.
             </p>
           </div>
         </div>
       </div>
       <div class="col-lg-4 col-md-6 mt--260">
         <div class="other-feature-item">
           <i class="ti-medall-alt"></i>
           <h4>Student Membership</h4>
           <div>
             <p>
               Lorem ipsum dolor sit amet consec tetur adipisicing elit, sed
               do eiusmod tempor incididunt labore. Lorem ipsum dolor sit
               amet consec tetur adipisicing elit, sed do eiusmod tempor
               incididunt labore.
             </p>
           </div>
         </div>
       </div>
       <div class="col-lg-4 col-md-6">
         <div class="other-feature-item">
           <i class="ti-briefcase"></i>
           <h4>35000+ Courses</h4>
           <div>
             <p>
               Lorem ipsum dolor sit amet consec tetur adipisicing elit, sed
               do eiusmod tempor incididunt labore. Lorem ipsum dolor sit
               amet consec tetur adipisicing elit, sed do eiusmod tempor
               incididunt labore.
             </p>
           </div>
         </div>
       </div>
       <div class="col-lg-4 col-md-6 mt--160">
         <div class="other-feature-item">
           <i class="ti-crown"></i>
           <h4>Expert Mentors</h4>
           <div>
             <p>
               Lorem ipsum dolor sit amet consec tetur adipisicing elit, sed
               do eiusmod tempor incididunt labore. Lorem ipsum dolor sit
               amet consec tetur adipisicing elit, sed do eiusmod tempor
               incididunt labore.
             </p>
           </div>
         </div>
       </div>
       <div class="col-lg-4 col-md-6 mt--260">
         <div class="other-feature-item">
           <i class="ti-headphone-alt"></i>
           <h4>Live Supports</h4>
           <div>
             <p>
               Lorem ipsum dolor sit amet consec tetur adipisicing elit, sed
               do eiusmod tempor incididunt labore. Lorem ipsum dolor sit
               amet consec tetur adipisicing elit, sed do eiusmod tempor
               incididunt labore.
             </p>
           </div>
         </div>
       </div>
     </div>
   </div>
 </section>
 <!-- ================ End Feature Area ================= -->

 <!-- ================ Start Testimonials Area ================= -->
 <section class="testimonials-area section-gap">
   <div class="container">
     <div class="testi-slider owl-carousel" data-slider-id="1">
       <div class="row align-items-center">
         <div class="col-lg-5">
           <div class="item">
             <div class="testi-item">
               <img src="{% static 'img/quote.jpg' %} alt="" />
               <div class="mt-40 text">
                 <p>
                   As conscious traveling Paup ers we must always be oncerned
                   about our dear Mother Earth. If you think about it, you
                   travel across her face and She is the host to your
                   journey.
                 </p>
               </div>
               <h4>Fanny Spencer</h4>
               <p>Chief Executive, Amazon</p>
             </div>
           </div>
         </div>

         <div class="offset-lg-1 col-lg-6">
           <img src="{% static 'img/testimonial/t1.jpg' %} alt="" />
         </div>
       </div>

       <div class="row align-items-center">
         <div class="col-lg-5">
           <div class="item">
             <div class="testi-item">
               <img src="{% static 'img/quote.jpg' %} alt="" />
               <div class="mt-40 text">
                 <p>
                   As conscious traveling Paup ers we must always be oncerned
                   about our dear Mother Earth. If you think about it, you
                   travel across her face <br />
                   and She is the host to your journey.
                 </p>
               </div>
               <h4>Fanny Spencer</h4>
               <p>Chief Executive, Amazon</p>
             </div>
           </div>
         </div>

         <div class="offset-lg-1 col-lg-6">
           <img src="{% static 'img/testimonial/t1.jpg' %} alt="" />
         </div>
       </div>
     </div>
   </div>
 </section>
 <!-- ================ End Testimonials Area ================= -->


{% endblock %}

ramu/tuition/templates/tuition/login.html
{% extends "tuition/base.html" %}
{% load static %}
{% block title %}
Sign Up Page
{% endblock %}

{% block body %}

<!-- ================ start banner Area ================= -->
  <section class="banner-area">
    <div class="container">
      <div class="row justify-content-center align-items-center">
        <div class="col-lg-12 banner-right">
          <h1 class="text-white">
            Feedback
          </h1>
          <p class="mx-auto text-white  mt-20 mb-40">
            Your feedback is of utmost importance to us!!!.
          </p>
          <div class="link-nav">
            <span class="box">
              <a href="index.html">Home </a>
              <i class="lnr lnr-arrow-right"></i>
              <a href="<?php echo base_url('feedback'); ?>">Feedback</a>
            </span>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ================ End banner Area ================= -->

  <!-- ================ Start Feature Area ================= -->
  <section class="feature-area">
    <div class="container-fluid">
      <div class="feature-inner row">
        <div class="col-lg-4 col-md-6">
          <div class="feature-item d-flex">
            <i class="ti-book"></i>
            <div class="ml-20">
              <form method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="Login">
  </form>
            </div>
          </div>
        </div>

      </div>
    </div>
  </section>
  <!-- ================ End Feature Area ================= -->



{% endblock %}